"use strict";
console.log("HEY ADU MUNIR HUSSAIN,I HAVE STARTED LEARNING TYPESCRIPY");
var myname = "Rashid munir";
console.log("My name is >=", myname);
var num1 = 1;
var num2 = 2;
var num3 = 3;
var num4 = 4;
var num5 = 5;
var num6 = 6;
var num7 = 7;
var num8 = 8;
var num9 = 9;
var num10 = 10;
var sum = num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10;
console.log("Sum is>=", sum);
var sub = num1 - num2 - num3 - num4 - num5 - num6 - num7 - num8 - num9 - num10;
console.log("Subtraction is >=", sub);
var munti = num1 * num2 * num3 * num4 * num5 * num6 * num7 * num8 * num9 * num10;
console.log("Multiplication is >=", munti);
var division = num10 / num5;
console.log("Division is >=", division);
var allop = num10 / num5 * num4 + num2 - num3;
console.log("All operation is >=", allop);
